Repository fit-trip/server, pull requests merged in 2022-11, with the labels that each got.

#9 Security 도입 전 유저 모델 추가
  src/main/java/com/example/mapp/user/dto/UserDto.java
  src/main/java/com/example/mapp/user/model/AppUser.java
  src/main/java/com/example/mapp/user/model/Role.java
  src/main/java/com/example/mapp/user/repository/UserRepository.java
  src/main/java/com/example/mapp/user/service/UserService.java
Labels: documentation, enhancement

#10 JWT 관리 추가, JWT 기반 Security 레이어 추가
  build.gradle
  src/main/java/com/example/mapp/auth/api/JwtAuthController.java
  src/main/java/com/example/mapp/auth/dto/TokenDto.java
  src/main/java/com/example/mapp/auth/service/JwtAuthService.java
  src/main/java/com/example/mapp/config/SecurityConfig.java
  src/main/java/com/example/mapp/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/mapp/security/provider/JwtProvider.java
  src/main/java/com/example/mapp/security/userdetails/AppUserDetails.java
  src/main/java/com/example/mapp/security/userdetails/AppUserDetailsService.java
  src/main/java/com/example/mapp/utils/JwtUtil.java
Labels: documentation, enhancement

#16 스케줄 공유 기능, 스케줄 반환 필드 추가
  src/main/java/com/example/mapp/route/dto/RouteInfoDto.java
  src/main/java/com/example/mapp/route/model/RouteInfoPerDuration.java
  src/main/java/com/example/mapp/route/service/RouteInfoService.java
  src/main/java/com/example/mapp/schedule/controller/ScheduleController.java
  src/main/java/com/example/mapp/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/example/mapp/schedule/dto/ScheduleUpdateDto.java
  src/main/java/com/example/mapp/schedule/model/Schedule.java
  src/main/java/com/example/mapp/schedule/repository/ScheduleRepository.java
  src/main/java/com/example/mapp/schedule/service/ScheduleService.java
Labels: documentation

#15 Feat: 스케쥴 ID로 최적 경로 조회 기능 추가
  src/main/java/com/example/mapp/route/api/RouteInfoController.java
  src/main/java/com/example/mapp/route/dto/RouteInfoResponseDto.java
  src/main/java/com/example/mapp/route/model/id/LocationId.java
  src/main/java/com/example/mapp/route/repository/RouteInfoPerDurationRepository.java
  src/main/java/com/example/mapp/route/repository/RouteInfoPerFareRepository.java
  src/main/java/com/example/mapp/route/service/RouteInfoService.java
  src/main/java/com/example/mapp/route/vo/CoordinateVo.java
  src/main/java/com/example/mapp/route/vo/RouteInfoVo.java
Labels: enhancement
